import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// components
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import styles from "../styles/sass/index.module.scss";

// assets
import hero from "../assets/images/hero.png";
import farmers from "../assets/images/farmers.png";
import insight from "../assets/images/insight.png";
import contribute from "../assets/images/contribute.png";
import calendar from "../assets/images/calendar.png";

import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from "react-accessible-accordion";

// Demo styles, see 'Styles' section below for some notes on use.
import "react-accessible-accordion/dist/fancy-example.css";

const ACCORDION_ITEMS = [
  {
    title: "Why Agrocist?",
    body: `
    Agrocist is building the largest technology driven
    agriculture experts community in Africa. 
    Be a part of the future of work in agriculture 
  `,
  },
  {
    title: "How it works",
    body: `
    Sign up and set up your profile. 
    It takes a few minutes to do that. 
    Start receiving bookings from farmers online. 
    and contribute freely to the online community to increase your 
    ratings
  `,
  },
  {
    title: "How to use Agrocist",
    body: `
    Agrocist expert community is built for farmers and agro experts in mind. Once you have successfully signed up, farmers will be able to access your profile and book your service online. 
    You get notifications in app and via emails once your service is booked which you are to confirm within 30 mins.
     Reach out to farmers accordingly via calls, farm visits etc to deliver your services to them 
  `,
  },
  {
    title: "Is Agrocist Free to use",
    body: `
    For now YES!  Though a premium will be placed in few months time. The earlier you sign up the better.
  `,
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Agrocist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <header className={styles.header}>
        <div className={` bloc `} id="bloc1">
          <span>
            <h1>A digital Community for agro experts</h1>
            <p>
              We are building an online community for veterinarians,
              agronomists, agriculturists etc that operate in agric value chain
            </p>
            <Link href={"/"}>Get Started</Link>
          </span>

          <Image src={hero} alt="" id="hero-img" />
        </div>
        <div className={` bloc `} id="bloc2"></div>
      </header>

      <section className={styles.section1}>
        <div className="container">
          <div className="grid">
            <div>
              <Image src={farmers} alt="farmers" />
            </div>

            <div>
              <h2>Worried about low customers and income?</h2>
              <p>
                Join our community to reach more farmers, access data insights
                and drive more sales
              </p>
              {/* <a href="https://drive.google.com/file/d/1SfZf3nb8V0OpDOPHD3UySNttITW5_89K/view?usp=drivesdk">
                Download
              </a> */}
              <Link href="/account/login">Get Started</Link>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section2}>
        <div className="container">
          <div className="grid">
            <div>
              <Image src={calendar} alt="" />
              <h3>Easy Paid Appointment</h3>
              <p>
                Receive paid bookings from farmers in need of your services and
                easily schedule a consultation time
              </p>
            </div>

            <div>
              <Image src={insight} alt="" />
              <h3>Data Insights</h3>
              <p>
                Access data insights to help improve your services and practices
              </p>
            </div>

            <div>
              <Image src={contribute} alt="" />
              <h3>Contribute</h3>
              <p>
                Contribute freely to the challenges of farmers online and get
                rated and noticed.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.faq}>
        <div className="container">
          <h2>Frequently asked question</h2>

          <Accordion>
            {ACCORDION_ITEMS.map((accordion) => {
              return (
                <AccordionItem>
                  <AccordionItemHeading>
                    <AccordionItemButton>{accordion.title}</AccordionItemButton>
                  </AccordionItemHeading>
                  <AccordionItemPanel>
                    <p>{accordion.body}</p>
                  </AccordionItemPanel>
                </AccordionItem>
              );
            })}
          </Accordion>
        </div>
      </section>

      <Footer />
    </>
  );
}
