import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/sass/index.module.scss";

// assets
import mobile from "../assets/images/mobile.png";
import smilingMan from "../assets/images/smiling-man.png";
import diagnose from "../assets/images/diagnose.svg";
import plant from "../assets/images/plant.svg";
import calendar from "../assets/images/calendar.svg";
import agronomist from "../assets/images/agronomist.png";

import disease from "../assets/images/crop-disease.png";
import chickens from "../assets/images/chickens.png";

import SocialCard from "../components/SocialCard";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agrocist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Navbar />
        <div id="jumbotron">
          <div>
            <h1>Farm advisory made easy, affordable and quick</h1>
            <p>
              With Agrocist, we help supercharge your agribusinesses using AI
              technology
            </p>
            <button>Download free</button>
          </div>

          <div>
            <Image src={mobile} alt="" />
          </div>
        </div>
      </header>

      <section className={styles.section1}>
        <div className="container">
          <div className="grid">
            <div>
              <h2>Free mobile Crop and Animal doctor</h2>
              <p>
                Using AI technology we help farmers diagnose and prevent pests
                and diseases one picture at a time.
              </p>
              <button>Download</button>
            </div>
            <div>
              <Image src={smilingMan} alt="A man smiling" />
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section2}>
        <div className="container">
          <div className="grid">
            <div>
              <Image src={diagnose} alt="" />
              <h3>Diagnose and Treat</h3>
              <p>
                Take the picture of your diseased plant/Animal and agrocist
                mobile app provides the diagnosis and treatments on the go
              </p>
            </div>

            <div>
              <Image src={plant} alt="" />
              <h3>AGRO Input</h3>
              <p>Locate a nearby Agro-Input in your Area.</p>
            </div>

            <div>
              <Image src={calendar} alt="" />
              <h3>Farm Calendar</h3>
              <p>
                Track all your farm activities with reminder notifications for
                easy farming experience
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section3}>
        <div className="container">
          <div className="grid">
            <div>
              <Image src={agronomist} alt="a farmer checking her crops" />
            </div>
            <div>
              <h2>Are you an agro expert agronomist or Vet?</h2>
              <p>
                As a an agronomist or a Vet, you can join our online community
                to access farmers, real time data insights and drive more sales
              </p>
              <button>Get started</button>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section4}>
        <div className="container">
          <div className="grid">
            <div>
              <h2>Join the Community</h2>
            </div>
            <div className="card-container">
              <SocialCard
                username={"Ajayi Paul"}
                location={"Osogbo, Osun state"}
                msg="
                My Crops started showing this since last 
                week and i dont know what to do. Please help"
                likes={110}
                comments={211}
                image={disease}
              />
              <SocialCard
                username={"Eze Ben"}
                location={"Nnewi, Abia state"}
                msg="
                My Crops started showing this since 
                last week and i dont know what to do. 
                Please help"
                likes={110}
                comments={211}
                image={chickens}
              />
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
